variables:
  - group : var-pipeline

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate
  displayName: 'Validation'
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.14.3'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          pwd 
          ls -ltr
          python3- -m pip install --upgrade pip
          pip3 install checkov
      displayName: 'Installing Checkov'

    - task: Bash@3
      inputs:
        targetType: inline
        script: |
          checkov -d terraform
      displayName: 'Security Scan'

- stage: Plan
  displayName: Terraform 'Plan'
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.14.3'

    - task: TerraformCLI@1
      displayName: 'Init'
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'azure-subs-terra'
        backendAzureRmResourceGroupName: 'terraform-rg'
        backendAzureRmStorageAccountName: 'mystoragesyedshah'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'afzal.tfstate'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'azure-subs-terra'

- stage: Apply
  displayName: Terraform 'Apply'
  dependsOn: Plan
  jobs:
  - job: Apply
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: '1.14.3'

    - task: TerraformCLI@1
      displayName: 'Init'
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'azure-subs-terra'
        backendAzureRmResourceGroupName: 'terraform-rg'
        backendAzureRmStorageAccountName: 'mystoragesyedshah'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'afzal.tfstate'

    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'azure-subs-terra'
